game_id: test1
name: 测试1
type: action
description: ''
author: ''
version: 1.0.0
icon: games/test1/assets/icons/photo_2024-09-12_02-08-20.jpg
tags: []
created_at: '2025-11-09 17:57:30'
updated_at: '2025-11-09 17:57:30'
