game_id: league_of_legends
name: 英雄联盟
type: moba
description: 全球最受欢迎的MOBA游戏，拥有众多特色英雄
author: 社区贡献者
version: '1.0'
icon: games/league_of_legends/assets/icons/LOL.png
tags: []
created_at: ''
updated_at: '2025-11-09 17:28:29'
